#ifndef GUARD_EGG_HATCH_CONSTANTS_H
#define GUARD_EGG_HATCH_CONSTANTS_H

#define EGG_STEP_MULTIPLIER_BASE           300
#define EGG_STEP_MULTIPLIER_ABILITY(x)     (3 * x / 2)
#define EGG_STEP_MULTIPLIER_MORNING(x)     x
#define EGG_STEP_MULTIPLIER_DAY(x)         (5 * x / 4)
#define EGG_STEP_MULTIPLIER_NIGHT(x)       (4 * x / 5)
#define EGG_STEP_MULTIPLIER_UNDERWATER(x)  (2 * x / 3)
#define EGG_STEP_MULTIPLIER_UNDERGROUND(x) (4 * x / 5)
#define EGG_STEP_MULTIPLIER_VOLCANO(x)     (3 * x / 2)

#define STEPS_PER_EGG_CYCLE (127 * EGG_STEP_MULTIPLIER_BASE)
#define EGG_STEPS_PER_BATTLE_TURN 32

#define EGG_HATCH_DEBUG FALSE

#endif //GUARD_EGG_HATCH_CONSTANTS_H
