#ifndef GUARD_EGG_HATCH_CONSTANTS_H
#define GUARD_EGG_HATCH_CONSTANTS_H

#define EGG_STEP_MULTIPLIER_BASE         300
#define EGG_STEP_MULTIPLIER_ABILITY      3 / 2
#define EGG_STEP_MULTIPLIER_MORNING      1
#define EGG_STEP_MULTIPLIER_DAY          5 / 4
#define EGG_STEP_MULTIPLIER_NIGHT        4 / 5
#define EGG_STEP_MULTIPLIER_UNDERWATER   2 / 3
#define EGG_STEP_MULTIPLIER_UNDERGROUND  4 / 5
#define EGG_STEP_MULTIPLIER_VOLCANO      3 / 2

#define STEPS_PER_EGG_CYCLE (192 * EGG_STEP_MULTIPLIER_BASE)
#define EGG_STEPS_PER_BATTLE_TURN 32

#define EGG_HATCH_DEBUG FALSE

#endif //GUARD_EGG_HATCH_CONSTANTS_H
