#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRACO_METEOR) \
    F(THUNDER_FANG) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(SNOWSTORM) \
    F(BULK_UP) \
    F(SEED_BOMB) \
    F(HIDDEN_POWER) \
    F(FLARE) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(ICE_FANG) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(GEYSER) \
    F(GIGA_DRAIN) \
    F(FIRE_FANG) \
    F(THUNDER_PUNCH) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(FIRE_PUNCH) \
    F(TRAILBLAZE) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(ICE_PUNCH) \
    F(REFLECT) \
    F(VOLT_SWITCH) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(LANDSLIDE) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(COUNTER) \
    F(FACADE) \
    F(PSYSHOCK) \
    F(REST) \
    F(NASTY_PLOT) \
    F(FOUL_PLAY) \
    F(STEEL_WING) \
    F(ZEN_HEADBUTT) \
    F(FLIP_TURN) \
    F(OVERHEAT) \
    F(ROOST) \
    F(FOCUS_BLAST) \
    F(ENERGY_BALL) \
    F(DEFOG) \
    F(SCALD) \
    F(TAILWIND) \
    F(KNOCK_OFF) \
    F(SIGNAL_BEAM) \
    F(BLOOM) \
    F(DRAIN_PUNCH) \
    F(WILL_O_WISP) \
    F(ACROBATICS) \
    F(HEAL_BELL) \
    F(EXPLOSION) \
    F(SHADOW_CLAW) \
    F(EARTH_POWER) \
    F(IRON_DEFENSE) \
    F(ENCORE) \
    F(ROCK_POLISH) \
    F(IRON_HEAD) \
    F(STONE_EDGE) \
    /**/F(AVALANCHE) \
    F(THUNDER_WAVE) \
    /**/F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(STEALTH_ROCK) \
    F(SPIKES) \
    F(HYPER_BEAM) \
    F(DARK_PULSE) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(SLEEP_TALK) \
    F(TOXIC_SPIKES) \
    F(POISON_JAB) \
    F(CRUNCH) \
    F(GRASS_KNOT) \
    F(HYPER_VOICE) \
    F(BODY_PRESS) \
    F(U_TURN) \
    F(SUBSTITUTE) \
    F(FLASH_CANNON) \
    F(TRICK_ROOM) \
    F(WILD_CHARGE) \
    /**/F(BUG_BUZZ) \
    F(AIR_SLASH) \
    F(HURRICANE) \
    F(PLAY_ROUGH) \
    F(GIGA_IMPACT) \
    F(DAZZLING_GLEAM) \
    F(GUNK_SHOT) \
    F(CLOSE_COMBAT) \
    /**/F(DRAGON_CLAW) \
    F(SURF) \
    F(STRENGTH) \
    F(SUPERPOWER) \
    /**/F(OUTRAGE) \
    F(WATERFALL) \
    /**/F(THIEF) \
    F(SEISMIC_TOSS) \
    F(VENOSHOCK) \
    F(AMNESIA) \
    /**/F(SLUDGE_WAVE) \
    F(SOLAR_BLADE) \
    F(HEX) \
    F(HOWLING_GALE) \
    /*r*/F(GRASSY_TERRAIN) \
    /*r*/F(ELECTRIC_TERRAIN) \
    /*r*/F(PSYCHIC_TERRAIN) \
    /*r*/F(MISTY_TERRAIN)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F)

#endif
