gText_ObtainedTheItem::
	.string "{STR_VAR_2} obtained!$"
	
gText_ObtainedTMHM::
	.string "Obtained {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The bag is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put the {STR_VAR_2}\n"
	.string "in {POSSESSIVE} bag's {STR_VAR_3} pocket.$"

gText_PlayerFoundOneItem::
	.string "{STR_VAR_2} found!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The bag is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} placed the {STR_VAR_2}\n"
	.string "in {POSSESSIVE} bag.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"
